// Generated by CoffeeScript 1.6.3
var filewatch, http, server;

http = require('http');

filewatch = require('./index');

server = http.createServer(function(req, res) {
  var options;
  options = {
    tryParseJson: true
  };
  return filewatch.watchTree("./testFolder", options, function(err, f, c, p, data) {
    if (err == null) {
      console.log("File changed " + f);
      return console.log("Data is " + data);
    }
  });
});

server.listen(3001);
